runtime: python
env: flex
runtime_config:
    python_version: 3
         
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8

resources:
    cpu: 1
    memory_gb: 6
    disk_size_gb: 10
