steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/fastapi-intro-repo/fastapi-intro-image', '.']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
      - sh
      - -c
      - |
        gcloud run deploy \
        fastapi-intro-$BRANCH_NAME \
        --image=gcr.io/$PROJECT_ID/fastapi-intro:latest \
        --cpu=2 \
        --memory=2048Mi \
        --timeout=600 \
        --concurrency=20 \
        --platform=managed \
        --max-instances=1000 \
        --allow-unauthenticated \
        --set-env-vars=PROJECT_ID=$PROJECT_ID,SHORT_SHA=$SHORT_SHA